version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - prometheus
      - redis
    networks:
      - monitoring
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    depends_on:
      - redis
    networks:
      - monitoring
    env_file:
      - .env

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight UI
    environment:
      - REDIS_ARGS=--requirepass yourStrongPassword
    networks:
      - monitoring
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supersecurepassword
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    env_file:
      - .env

volumes:
  grafana_data:

networks:
  monitoring:
    driver: bridge
