# Ruff configuration file
# See: https://docs.astral.sh/ruff/configuration/

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.8+
target-version = "py38"

[lint]
# Enable Pyflakes (`F`) and a subset of isort (`I`) codes.
# Unlike Flake8, Ruff doesn't enable pycodestyle (`E`) and Pyflakes (`F`) by default.
# Ruff also fixes E501 by default, which is why we disable it above.
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]

# Never enforce `E501` (line length violations).
ignore = [
    "E501",  # Line too long
    "B008",  # Function call in default argument - FastAPI dependency injection pattern
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto" 